name: Publish Release

on:
  workflow_dispatch:
  push:
    tags:
      - 'luma-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: 'go.mod'

      - name: Build
        if: startsWith(github.ref, 'refs/tags/')
        run: make -j releases